ALTER TABLE users ADD COLUMN IF NOT EXISTS is_moderator BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_founder BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS founder_discount_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS discount_percent INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS discount_label TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS discount_expires_at TIMESTAMPTZ;
